### ISSUE TITLE
Feature Request - Raid frames and party frames

### ISSUE THREAD

**Issue by PerfectByte** [cogwerkz/DiabolicUI#92] opened 2017-12-23 09:13 UTC

**Comment by serberus7** [comment] 2018-01-12 03:39
yeah this was actually difficult to get back
Comment out line 61 in unitframes.lua
Then erase target.lua completely
Then comment lines 73 through 134 in unitframes.lua

That should do it.
I'm about to find a unitframes addon now that I have the old ones back
I mean no need to have a unit frame for your own character since you have the cool orbs at the bottom of the screen anyway...
I did like the target unit frames for diabolicUI but there were no buffs or target of target...
eh... :\

https://pasteboard.co/H2wxosA.png

**Comment by goldpaw** [comment] 2018-01-30 05:41
This is a duplicate of an issue I started myself a long time ago. 
https://github.com/cogwerkz/DiabolicUI/issues/12
#12

**Closed by goldpaw** 2018-01-30 05:41 UTC
